### ISSUE TITLE
Support for MP3 output

### ISSUE THREAD

**Issue by chubbard** [watson-developer-cloud/text-to-speech-nodejs#11]
Add support for MP3 output (doesn't have to be streamed).  Currently greatest support for audio support in HTML is through MP3.  Ogg is only supported by a few browsers.  If we had MP3 support it would be easier to use this service in our product.

**Comment by daniel-bolanos** [comment]
Yes, you are right, there are other users demanding that. I will check...

**Comment by daniel-bolanos** [comment]
Hello Chubbard, unfortunately, because of licensing issues, there are no plans to release support for mp3 in the TTS service. It is not ideal but you might want to take a look at doing the conversion yourself. On the server side it is easy with ffmpeg, on the client side with javascript you could try something like this: http://stackoverflow.com/questions/17457029/converting-wav-to-any-compressed-audio-format-in-client-side-javascript

please keep us posted on your progress

**Comment by chubbard** [comment]
Ok I felt like this was the case.  And converting it myself was my workaround to this issue.

**Comment by daniel-bolanos** [comment]
good, please let us know what conversion approach works best for you. I suspect other developers are going to run into the same issue.

thank you

**Comment by doctoratlantis** [comment]
Is the licensing issue still valid? I had read that most all .mp3 patents expired in the US as of April 2017? Seems like .mp3 output would be a big boost for the widespread use of the output.

**Comment by playground** [comment]
Is .mp3 output supported?

**Comment by germanattanasio** [comment]
Yes
